spring:
  application:
    name: comic
  jackson:
    property-naming-strategy: SNAKE_CASE
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/marvel-comic

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-witch-eureka: true

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  listOfServers: localhost:8081

kafka:
  bootstrapAddress: localhost:9092
  topic:
    comic-events: ${spring.profiles.active:dev}.comic-events
    character-update-events: ${spring.profiles.active:dev}.character-update-events
    character-remove-events: ${spring.profiles.active:dev}.character-remove-events
